apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: ravinmuthukumarane/bff-service:1.0.0
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: IDENTITY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: IDENTITY_SERVICE_URL
            - name: SALARY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SALARY_SERVICE_URL
            - name: VOTE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VOTE_SERVICE_URL
            - name: SEARCH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SEARCH_SERVICE_URL
            - name: STATS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: STATS_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 20
            periodSeconds: 20
