FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY .env ./.env
COPY src ./src

USER node

EXPOSE 5005

CMD ["npm", "start"]
