apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: nipuniamarasinghe/vote-service:1.0.0
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: DB_PASSWORD
            - name: APPROVAL_UPVOTE_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APPROVAL_UPVOTE_THRESHOLD
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 30
            periodSeconds: 20
